(function(){"use strict";
const sources=[
  ["about-purpose-mother-child.webp","community"],["ambulance-service.webp","care"],["ambulance-support.webp","care"],["community-children.webp","community"],["community-meal-support.webp","food"],["community-outreach.webp","community"],["csr-ambulance.webp","care"],["csr-closing-girl.webp","community"],["csr-closing.webp","community"],["csr-community-voice-01.webp","community"],["csr-community-voice-02.webp","community"],["csr-elderly-care.webp","care"],["csr-employee-volunteering.webp","community"],["csr-focus-ambulance.webp","care"],["csr-focus-elderly.webp","care"],["csr-focus-food.webp","food"],["csr-focus-last-rites.webp","care"],["csr-food-support.webp","food"],["csr-hero-community.webp","community"],["csr-last-rites.webp","care"],["csr-program-support.webp","community"],["csr-programme-support.webp","community"],["csr-purpose-child.webp","education"],["csr-purpose-main.webp","community"],["csr-purpose-overlap.webp","community"],["csr-voice-elderly.webp","care"],["csr-voice-student.webp","education"],["csr-volunteering.webp","community"],["csr-way-fund-programme.webp","community"],["csr-way-long-term.webp","community"],["csr-way-resource-support.webp","community"],["csr-way-volunteering.webp","community"],["dignified-last-rites.png","care"],["education-support.webp","education"],["elderly-care.webp","care"],["elderly-man.webp","care"],["elderly-woman-care.webp","care"],["healthcare-support.webp","care"],["impact-children.webp","education"],["impact-elderly-man.webp","care"],["meal-distribution.webp","food"],["mission-vision-journey-bg.webp","community"],["our-impact-sunset-village.png","community"],["vision-schoolgirl.webp","education"]
];
const grid=document.getElementById("gallery-grid"),lightbox=document.getElementById("gallery-lightbox"),image=document.getElementById("lightbox-image"),title=document.getElementById("lightbox-title"),category=document.getElementById("lightbox-category"),counter=document.getElementById("lightbox-counter"),close=document.querySelector(".mjks-gallery__close");let items=[],visible=[],active=0,startX=0;
function label(file){return file.replace(/\.(webp|png|jpg|jpeg)$/i,"").replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function render(){grid.innerHTML="";items=sources.map(([file,type])=>{const button=document.createElement("button");button.type="button";button.className="mjks-gallery__item";button.dataset.category=type;button.dataset.title=label(file);button.dataset.image="assets/"+file;const img=document.createElement("img");img.src=button.dataset.image;img.alt=label(file)+" from Manav Janhit Kalyan Sansthan";img.loading="lazy";button.append(img);grid.append(button);return button});sync()}
function sync(){visible=items.filter(item=>!item.classList.contains("is-hidden"))}
function show(index){sync();if(!visible.length)return;active=(index+visible.length)%visible.length;const item=visible[active];image.src=item.dataset.image;image.alt=item.querySelector("img").alt;title.textContent=item.dataset.title;category.textContent="";counter.textContent=`${active+1} / ${visible.length}`;lightbox.classList.add("is-open");lightbox.setAttribute("aria-hidden","false");document.documentElement.style.overflow="hidden";close.focus()}
function hide(){lightbox.classList.remove("is-open");lightbox.setAttribute("aria-hidden","true");document.documentElement.style.overflow=""}
function move(step){show(active+step)}
grid.addEventListener("click",event=>{const item=event.target.closest(".mjks-gallery__item");if(item)show(visible.indexOf(item))});document.querySelector(".mjks-gallery__filters").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;document.querySelectorAll(".mjks-gallery__filters button").forEach(item=>{const state=item===button;item.classList.toggle("is-active",state);item.setAttribute("aria-pressed",String(state))});const filter=button.dataset.filter;items.forEach(item=>item.classList.toggle("is-hidden",filter!=="all"&&item.dataset.category!==filter));sync()});document.querySelector(".mjks-gallery__arrow--prev").addEventListener("click",()=>move(-1));document.querySelector(".mjks-gallery__arrow--next").addEventListener("click",()=>move(1));close.addEventListener("click",hide);lightbox.addEventListener("click",event=>{if(event.target===lightbox)hide()});document.addEventListener("keydown",event=>{if(!lightbox.classList.contains("is-open"))return;if(event.key==="Escape")hide();if(event.key==="ArrowRight")move(1);if(event.key==="ArrowLeft")move(-1)});lightbox.addEventListener("touchstart",event=>{startX=event.touches[0].clientX},{passive:true});lightbox.addEventListener("touchend",event=>{const diff=startX-event.changedTouches[0].clientX;if(Math.abs(diff)>50)move(diff>0?1:-1)},{passive:true});render();
})();
